extend ExportArtifacts params
refractionPOINT/go-limacharlie pull request #142
Opened 2024-01-10 19:18 UTC by adele-lc

## Description of the change

Extended logic in function to include optional query parameters in API call. 
Intent to blend in some of the [GetOriginal](https://github.com/refractionPOINT/python-limacharlie/blob/master/limacharlie/Logs.py#L142C72-L142C86) capabilities from old python code

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Enhancement

2024-01-10 19:21 UTC, maximelb requested changes
Small data type tweak.

2024-01-10 19:21 UTC, maximelb commented on limacharlie/artifact.go
> +func (org Organization) ExportArtifact(artifactID string, deadline time.Time, optParams *interface{}) (io.ReadCloser, error) {
```suggestion
func (org Organization) ExportArtifact(artifactID string, deadline time.Time, optParams Dict{}) (io.ReadCloser, error) {
```
A simple Dict of key-val will do. Also note that `interface{}` (an interface) is always just a referemce/pointer to a value, so the `*` is superfluous.

2024-01-10 19:37 UTC, maximelb approved these changes, later dismissed

2024-01-11 00:11 UTC, maximelb submitted a review, later dismissed

2024-01-11 17:35 UTC, maximelb approved these changes

2024-01-11 17:36 UTC, merged

2024-01-12 19:00 UTC, josh-lc reviewed
LGTM